version: '2' 
services:
  
  proxy:
    build: ./nginx
    ports:
      - "5000:3000"
    container_name: balancer_fork

  db:
    image: mongo
    volumes:
      - "/var/mongo-data-fork:/data/db"
      - "/var/mongo-backup:/opt"
    restart: on-failure
    container_name: database_fork
  
  app:
      build:
        context: .
        args:
          NODE_URL: http://icoworld.projects.oktend.com:8545
          PORT: 3000
          DB_URI: mongodb://db:27017/ico_world_db
      image: ico/backend:$BUILD_ID
  backend-1:
    extends:
      service: app
  backend-2:
    extends:
      service: app
